import { pt_serif } from "@/lib/fonts";
import "./globals.css";
import type { Metadata } from "next";
import { Navbar } from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${pt_serif.className} px-4`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
